#ifndef CDH_ERROR_CODES_H
#define CDH_ERROR_CODES_H

#define CDH_NULL_MALLOC_OUPUT   0xCD000
#define CDH_NULL_REALLOC_OUTPUT 0xCD001
#define CDH_NULL_CALLOC_OUTPUT  0xCD002

#endif // CDH_ERROR_CODES_H